### ISSUE TITLE
best set of dependencies and hardware environment

### ISSUE THREAD

**Issue by adamsj-ros** [RobotecAI/RobotecGPULidar#171]
I've been attempting to build and run this on multiple platforms including Orin AGX, WSL2 (with Nvidia support Ubuntu 22.04), Azure cloud with a Tesla T4, PopOS 22.04 with Nvidia GeForce GTX 1050, and Ubuntu 22.04 with Nvidia GeForce GTX 1050. I've been trying docker and Ubuntu builds. There have been various reason why many of these aren't working. I'm not done with all combinations, but I'm wondering if there is a recommended hardware, OS, Nvidia driver, and CUDA runtime combination that is most recommended/tested. The matrix of combinations and time to setup causes a lot of pain trying to get something that works.

**Comment by adamsj-ros** [comment]
Update: Missed a step that I can select the version of CUDA toolkit instead of using the apt registry default.

**Comment by msz-rai** [comment]
Thank you for trying out our library.

We are developing a project using
- Nvidia GPUs RTX Series (20, 30, and 40),
  - But it should work on any Nvidia GPU
- Ubuntu 22.04 and Windows 10/11
- CUDA Toolkit 11.7 on Ubuntu and 11.4.4 on Windows
- NVIDIA OptiX 7.2

This setup is the most tested. We recommend building on Ubuntu (on the host side) following [the instructions](https://github.com/RobotecAI/RobotecGPULidar#building-on-ubuntu-22).

> There have been various reason why many of these aren't working.

Could you provide more details on errors you have encountered?
