### ISSUE TITLE
clean docker build but docker run issue

### ISSUE THREAD

**Issue by adamsj-ros** [RobotecAI/RobotecGPULidar#172]
Has anyone encountered this issue on run?

```
❯ docker run --net=host --gpus all -v $(pwd):/code -v ${OptiX_INSTALL_DIR}:/optix -e OptiX_INSTALL_DIR=/optix -e NVIDIA_DRIVER_CAPABILITIES=all -it rgl:latest /bin/bash
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: container error: cgroup subsystem devices not found: unknown.
ERRO[0000] error waiting for container: context canceled
````

**Comment by msz-rai** [comment]
We have never seen this error before.
To help us find the problem, please provide your:
- OS version
- GPU model
- GPU driver version

If you are working on PopOS, [this comment](https://github.com/NVIDIA/nvidia-docker/issues/1660#issuecomment-1437203825) can help you.

**Comment by adamsj-ros** [comment]
I tried again on a different machine with a modern Nvidia GPU and it seems to work although the next step in the `README.md` doesn't work. 

. I did notice that `--runtime=nvidia` was missing to use `--gpus all` but maybe that's not a problem depending on how you've setup docker with Nvidia.
