### ISSUE TITLE
Inquiry Regarding Docker Building Support In China

### ISSUE THREAD

**Issue by Niloux3d** [RobotecAI/RobotecGPULidar#228]
Hello, I am relatively new to the this area. Nowadays I have encountered challenges while using vcpkg to install the necessary dependencies due to my location in China. I am wondering if there is a pre-existing Docker image available or if it would be feasible to create and share one. This would greatly facilitate the installation process for users in regions with restricted access to certain dependencies. Thx

**Comment by PawelLiberadzki** [comment]
@Niloux3d Thank you for pointing out this issue! Unfortunately, currently we do not have Docker image with our LiDAR and there are no tasks planned to add one in the nearest future. Nonetheless, we definitely agree that this would be a significant gain and that we should add Docker image at some point.
