### ISSUE TITLE
Integration into IsaacSim

### ISSUE THREAD

**Issue by philRudd69** [RobotecAI/RobotecGPULidar#244]
Hi,

at the company I work for, we are using Nvidia IsaacSim as a robotics simulation tool and I am wondering whether it could be possible to use your raytracing software in an self-coded "Lidar sensor extension" for IsaacSim.
I am asking because I recently managed to use the PhysX SceneQuery interface for IsaacSim to perform a raycast, but you claim that your approach might be much faster and that your approach does not depend on the PhysX colliders.
As a side-note: In IsaacSim 3D scenes are represented in Pixar's USD format. 
Can you make an educated guess whether this could work or not? And do you have any recommendations where to start for such a project?
Thx a lot.

Markus

**Comment by PawelLiberadzki** [comment]
Hi @philRudd69,

Using RGL this way is possible and my rough guess is that it should work much more effectively than PhysX SceneQuery. Very similar case takes place in Open 3D Engine, where PhysX is used for querying scene by default, but we also successfully integrated and actively use RGL for LiDAR sensor.

You can start with [general usage docs](https://github.com/RobotecAI/RobotecGPULidar/blob/develop/docs/Usage.md) and then follow hyperlink at the bottom to check, how the API is documented. Then, I recommend checking available RGL integrations into:
- [O3DE](https://github.com/RobotecAI/o3de-rgl-gem)
- [Gazebo](https://github.com/RobotecAI/RGLGazeboPlugin)
- [Unity](https://github.com/tier4/AWSIM/tree/main/Assets/RGLUnityPlugin)

O3DE RGL Gem is probably the closest to what you are willing to achieve.

Best regards,
Pawel

**Comment by adamdbrw** [comment]
We built 3 such plugins as @PawelLiberadzki mentions and are very effective at doing it. @philRudd69 if you wish to discuss possibilities or simply have a technical discussion reach out to me at adam.dabrowski@robotec.ai, we can setup a call.
