### ISSUE TITLE
Support For Ubuntu 18/20 and ROS

### ISSUE THREAD

**Issue by Hrithik-verma** [RobotecAI/RobotecGPULidar#269]
I was try to implement this plugin for [ ROS UNITY ](https://github.com/Unity-Technologies/ROS-TCP-Endpoint) but in Ubuntu 18/20. I found issue with .so files. Its a request to provide api support for ubuntu 18/20 because this package seems very promising for lidar in unity. As well please make support  [ ROS UNITY ](https://github.com/Unity-Technologies/ROS-TCP-Endpoint) because this package has better ros support for both ros / ros2 or make a stand alone package without ros2 dependency so that other can try it with ros as well.

Thanks in advance. Very good package support for gpu lidars and hoping to see good work in it in future.

**Comment by prybicki** [comment]
Hi @Hrithik-verma 

> Its a request to provide api support for ubuntu 18/20 because this package seems very promising for lidar in unity.

Ubuntu 18 is already past its end-of-life date, and Ubuntu 20 will reach it next year, so we don't see any benefit from supporting these versions.

> As well please make support [ROS UNITY ](https://github.com/Unity-Technologies/ROS-TCP-Endpoint)because this package has better ros support for both ros / ros2 or make a stand alone package without ros2 dependency so that other can try it with ros as well.

It may be helpful to have a look on our [RGLUnityPlugin](https://github.com/tier4/AWSIM/tree/main/Assets/RGLUnityPlugin) and [Ros2ForUnity](https://github.com/RobotecAI/ros2-for-unity) projects.
