### ISSUE TITLE
Build error on Windows - identifier "M_PIf" is undefined

### ISSUE THREAD

**Issue by AlgoryxJosef** [RobotecAI/RobotecGPULidar#271]
Building the develop branch on Windows, Visual Studio 2019. Commit 1cc5becd25585282c685c169f720221c834056b3.

Have tried Cuda Toolkit version 11.4.4 and 11.8.89, as well as Optix 7.2 and 7.6, in all combinations.

Error:  

`C:\Users\Admin\git\fork\RobotecGPULidar\src\gpu\nodeKernels.cu(108): error: identifier "M_PIf" is undefined`
 
I suppose some include is missing, but I could not for the life of me figure out which one. On Linux I guess M_PIf is defined, but not on Windows. 
Have fixed this locally by simply hard-coding 3.141592f, but a real solution would be great.  

Side note: I also hit upon another build error, but managed to fix that one, have created a PR for it: https://github.com/RobotecAI/RobotecGPULidar/pull/270

**Comment by msz-rai** [comment]
Fixed with https://github.com/RobotecAI/RobotecGPULidar/pull/272
