### ISSUE TITLE
Pointcloud message type incompatibility with Autoware

### ISSUE THREAD

**Issue by Aysenayilmaz** [RobotecAI/RobotecGPULidar#313]
With https://github.com/autowarefoundation/autoware.universe/pull/6996, the pointcloud types have been changed. They have transitioned from using _PointXYZI_ to _PointXYZIRCAEDT_. 

```
- X: x   
- Y: y
- z: z
- I: intensity
- R: ring
- A :azimuth
- D: distance
- T: time_stamp
```
As a result, pointcloud types are no longer supported by the RobotecGPULidar.
### Current point types:  
```
- 'x'  FLOAT32
- 'y' FLOAT32
- 'z'  FLOAT32
- 'intensity'  FLOAT32
- 'ring' UINT16
- 'azimuth'  FLOAT32
- 'distance' FLOAT32
- 'return_type' UINT8
- 'time_stamp' FLOAT64
```
### Data types used in Autoware:   
https://github.com/autowarefoundation/autoware.universe/blob/9f41bf13d9e8a73d2bfd6278cc249e2306348c1e/common/autoware_point_types/include/autoware_point_types/types.hpp#L95
```
- x,y,z  float   	 
- intensity  uint8_t   	 
- return_type  uint8_t   	 
- channel  uint16_t    
- azimuth  float   	 
- elvation   float   	 
- distance  float   	 
- time_stamp   uint32_t 
```   
That's why there is a https://github.com/autowarefoundation/AWSIM-Labs/issues/114 problem in AWsim Labs. 
The error I get when I run Autoware and AWsim Labs:
`[component_container-30] [ERROR] [1720621336.877892482] [sensing.lidar.top.crop_box_filter_self]: The pointcloud layout is not compatible with PointXYZIRCAEDT/PointXYZIRC. Aborting`

**Comment by prybicki** [comment]
@Aysenayilmaz This is not an RGL issue. Pointcloud format in RGL is configurable in runtime using `rgl_node_points_format`. Therefore I'd recommend to have a look at the code that's using RGL, most likely [here](https://github.com/autowarefoundation/AWSIM-Labs/tree/main/Assets/AWSIM/Scripts/Sensors/LiDAR).

**Comment by msz-rai** [comment]
@Aysenayilmaz 

We initially underestimated the issue, failing to recognize that the field types had also changed. This necessitates the implementation of data type conversions in the native library. We are addressing this and will implement the necessary changes as soon as possible.

**Comment by Aysenayilmaz** [comment]
@prybicki I have reviewed these files, but unfortunately, I cannot modify the content of the message. The GPULidar library is used in the Lidar publisher. I am sharing the content of the message published on the /sensing/lidar/top/pointcloud_raw_ex topic:

_$ ros2 topic echo  /sensing/lidar/top/pointcloud_raw_ex --field fields_

`[sensor_msgs.msg.PointField(name='x', offset=0, datatype=7, count=1), sensor_msgs.msg.PointField(name='y', offset=4, datatype=7, count=1), sensor_msgs.msg.PointField(name='z', offset=8, datatype=7, count=1), sensor_msgs.msg.PointField(name='intensity', offset=16, datatype=7, count=1), sensor_msgs.msg.PointField(name='ring', offset=20, datatype=4, count=1), sensor_msgs.msg.PointField(name='azimuth', offset=24, datatype=7, count=1), sensor_msgs.msg.PointField(name='distance', offset=28, datatype=7, count=1), sensor_msgs.msg.PointField(name='return_type', offset=32, datatype=2, count=1), sensor_msgs.msg.PointField(name='time_stamp', offset=40, datatype=8, count=1)]`

**The parts that need to be changed are as follows:**

- The **intensity** type should be changed from `float32` to `uint8_t`.
- The name of **ring** should be changed to `channel`.
- The **time_stamp** type should be changed from `float64` to `uint32_t`.

**Comment by xmfcx** [comment]
https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/sensing/data-types/point-cloud/#point-cloud-fields

This page has also been updated with the latest changes.

**Comment by Aysenayilmaz** [comment]
Thank you very much for the quick response. When I build the current version and add it to AWsim-Labs, I get such an error. 

![Screenshot from 2024-07-19 18-46-43](https://github.com/user-attachments/assets/e9f108e1-935a-4737-afa1-c460e86e75b7)

It cannot find the function "rgl_node_points_ros2_publish_with_qos". Could I be taking the wrong build?

**Comment by msz-rai** [comment]
@Aysenayilmaz 
The error you got most likely means that you provided RGL binary without ROS2 extension (build with the command `./setup.py`)

When we build RGL for AWSIM we use the following command:
```
./setup.py --with-pcl --with-ros2-standalone --lib-rpath \$ORIGIN/../../../../Ros2ForUnity/Plugins/Linux/x86_64
```
The additional rpath option is for dependent ROS2 libraries that are shared with the `Ros2ForUnity` plugin. This way we point out the location where the RGL binary should search for ROS2 libraries.

The deploy:
1. Copy `RobotecGPULidar` binary to `RGLUnityPlugin`:
```
cp build/lib/libRobotecGPULidar.so {AWSIM-path}/Assets/RGLUnityPlugin/Plugins/Linux/x86_64/
```
2. Copy new ROS2 libraries to `Ros2ForUnity`
```
cp -n build/lib/ros2_standalone/lib* {AWSIM-path}/Assets/Ros2ForUnity/Plugins/Linux/x86_64/
```

**Comment by msz-rai** [comment]
I am closing the ticket since the issue has already been resolved on the library side :heavy_check_mark:

**Comment by feng123a52** [comment]
请问使用禾赛的激光雷达实车在外部传入自己的点云数据，autoware出现了这么个错，The pointcloud layout is not compatible with PointXYZIRCAEDT/PointXYZIRC. Aborting该如何解决
