### ISSUE TITLE
The pointcloud layout is not compatible with PointXYZIRCAEDT/PointXYZIRC. Aborting

### ISSUE THREAD

**Issue by feng123a52** [RobotecAI/RobotecGPULidar#323]
我用的是禾赛的32线的激光雷达请问如何解决这个问题

**Comment by PawelLiberadzki** [comment]
Hi @feng123a52. There is not a lot of details here, however I assume that you have a problem with latests updates to point cloud format. There is a topic on The Autoware Foundation [here](https://github.com/orgs/autowarefoundation/discussions/5031) that you may follow for more information.
