### ISSUE TITLE
Reflections and transparent materials

### ISSUE THREAD

**Issue by u-sj** [RobotecAI/RobotecGPULidar#326]
Are there any plans for supporting transparent materials and total internal reflections in the future? Would that be feasible? Would a simple implementation require anything else besides a refractive index for objects from an user point of view? (and manifold mesh probably)

I think this would be desirable at least in automotive use cases, as cars tend to have quite a lot of glass surface area. I've seen a fair share of issues with object detection caused by reflections.

**Comment by PawelLiberadzki** [comment]
Hi @u-sj! I can say that there is a concept for introducing this (behavior of light at an interface between different media), but at this moment it is not in our plans for incoming months.

> Would that be feasible? Would a simple implementation require...

Yes, this would be feasible. Refractive index would be a part of such implementation. However, the most significant updates have to be made to raytracing code, with some updates to data management. It should not be a very complex task, but rather far from easy - depending i.a. on how accurately we would like to handle different phenomena.

>  I think this would be desirable at least in automotive use cases...

Definitely, I agree on this.

**Comment by u-sj** [comment]
Good to hear! I don't have an immediate need for this feature, but knowing this gives me more confidence to continue with this library. I've been very impressed so far.

**Comment by PawelLiberadzki** [comment]
Thank you, great to hear that! Feel free to ask questions if you will have any other issues in the future. Best regards!
