### ISSUE TITLE
How to temporarily hide an entity?

### ISSUE THREAD

**Issue by u-sj** [RobotecAI/RobotecGPULidar#331]
Hello

What would be the best way of temporarily hiding entities from a scene? Currently it seems that destroying and recreating the entity is the only way. Does this have overhead that a dedicated API call could avoid?

Thanks.

**Comment by prybicki** [comment]
Hi,

Yes, currently the only way to manage entities is by creating and destroying them. However, entities are lightweight objects, so the overhead for creating or destroying them is minimal. The more significant performance cost comes from rebuilding the OptiX Acceleration Structures, but this is necessary whenever an entity is updated.

If you're open to coding, I suggest experimenting with visibility masks in OptixInstance and rays. This approach might allow you to hide entities without needing to destroy and recreate them.
