### ISSUE TITLE
lidar simulation principle

### ISSUE THREAD

**Issue by HuangVictorAuto** [RobotecAI/RobotecGPULidar#340]
Hello, thanks for the great work of lidar simulation with raycasting on GPU.
do you have a detailed backend model description of the lidar simulation? like the one we saw in Carlar lidar.
like, how distance/lidar wavelenth/ incident target angle/target material/ multi return / motion distortion is considered and modelled?

**Comment by prybicki** [comment]
Hi @HuangVictorAuto!

As for the intensity, RGL provides a very simple model - a readout from user-provided texture multiplied by the cosine of incident angle.
Motion distortion is implemented via distorting ray pattern, but the computation still occurs on a static scene - so only the lidar's velocity is taken into account.
Multi-return is implemented via ray subsampling (roughly uniform) inside the laser beam cone.

If you are interested in more advanced lidar simulation, please reach out to us via an email.
